using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TalentoPlus.Application.Interfaces;
using TalentoPlus.Domain.Entities;

namespace TalentoPlus.Infrastructure.Services;

public class PdfService : IPdfService
{
    public PdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateEmployeeResume(Employee employee)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header()
                    .Text($"Resume: {employee.FirstName} {employee.LastName}")
                    .SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(x =>
                    {
                        x.Spacing(10);

                        x.Item().Text($"Position: {employee.Position}");
                        x.Item().Text($"Email: {employee.Email}");
                        x.Item().Text($"Phone: {employee.PhoneNumber}");
                        x.Item().Text($"Department: {employee.Department?.Name ?? "N/A"}");
                        x.Item().Text($"Education: {employee.Education}");
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by TalentoPlus System");
                        x.Span($" - {DateTime.Now:d}");
                    });
            });
        }).GeneratePdf();
    }
}
